### PR TITLE
Fix badges

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *Badges don't show : as now they are available without ` (Apps)`*

## Solution
- *Remove ` (Apps)`*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

### CODE REVIEW

**Review by ericgaspar — APPROVED** [review]

**Comment by alexAubin** [comment]
Ugh ... didn't realize that ... can probably work on a small autopatch to fix this on all apps at once

**Comment by yalh76** [comment]
> 
> 
> Ugh ... didn't realize that ... can probably work on a small autopatch to fix this on all apps at once

not a big deal as there is already badges at the beginning of the readme...

Maybe we should remove that part of the read me, as there is no ARM Ci for now ^^

**Comment by alexAubin** [comment]
Ah, I thought this was about the badges at the top

Yup, that section doesn't make much sense until we really have a reliable live ARM CI :/

**Comment by yalh76** [comment]
For the top part I managed the status and maintain badge in https://github.com/YunoHost/CI_package_check/pull/34... and apply in ci-apps ... thoses badges were not more available ^^

**Pull request merged**
