### PR TITLE
Adding license informations

### PR DESCRIPTION
**Pull request by yalh76**

### CODE REVIEW

**Comment by JimboJoe** [comment]
I'm wondering if it's a good idea to have this information, provided it's already in the manifest... :thinking:

**Comment by yalh76** [comment]
Well the [package_linter](https://github.com/YunoHost/package_linter/blob/master/package_linter.py) ask for....
capture

**Comment by alexAubin** [comment]
Note that it's only if the license field is "free", "non-free" or "dep-non-free" : https://github.com/YunoHost/package_linter/blob/master/package_linter.py#L219-L220

If you put e.g. GPL3.0 (dunno the exact syntax) it's okay

**Comment by yalh76** [comment]
My bad, I remove that Pull Request

**Comment by alexAubin** [comment]
Well maybe we can make the package linter's message that you mention more explicit about this tho. Maybe it's not so obvious that the alternative is to put something else than just "free" in this field

**Comment by yalh76** [comment]
I think the package_linter is enough explicit, I just read it too quickly
`[YEP-1.3] The use of 'free' in license field implies to write something about the license in your README.md`

**Pull request closed without merging**
