### PR TITLE
Add License as default

### PR DESCRIPTION
**Pull request by ericgaspar**
- Add license GNU AFFERO GENERAL PUBLIC LICENSE Version 3 as default

### CODE REVIEW

**Comment by ericgaspar** [comment]
May I ask why so much confusion?  Is GNU AFFERO GENERAL PUBLIC LICENSE Version 3 not the default for YunoHost package? packager can always put something else. This is a guideline.

**Comment by yalh76** [comment]
as far as I know, there is no default licence for YunoHost packages

**Comment by ericgaspar** [comment]
> as far as I know, there is no default licence for YunoHost packages

This PR adresses the lack default licence. A very large majority of licence are AGPL-3.0, making It the _the facto_ licence.

**Comment by yalh76** [comment]
> > as far as I know, there is no default licence for YunoHost packages
> 
> This PR addresses the lack of default licence. A very large majority of licence are AGPL-3.0, making It the _the facto_ licence.

Do you some statistics about that? like for each licence used by packages, the number of time that licence is used ?

**Comment by ericgaspar** [comment]
I do not have proper metrics (as per specific percentage)
The license file is confusing because you don't know which license to use... Sometimes packagers put upstream app licenses. 
[wemawema_ynh](https://github.com/YunoHost-Apps/wemawema_ynh) is intentionally using a specific license

**Pull request closed without merging**
