### PR TITLE
updated

### PR DESCRIPTION
**Pull request by garwinch**

### CODE REVIEW

**Comment by opi** [comment]
Thanks for working on cagette packaging !

However, you should not open a pull-request on the example_ynh app, but instead create your own github repository (https://github.com/YunoHost/cagette_ynh or https://github.com/garwinch/cagette_ynh).

If you're in trouble with this procedure, feel free to come and talk to us: http://yunohost.org/support

**Comment by garwinch** [comment]
sorry gays, was just a wrong start :-)

**Comment by M5oul** [comment]
gays or guys? 😄

**Comment by garwinch** [comment]
Hoops sorry guys !!! :-D

**Pull request closed without merging**
