### PR TITLE
fix db_user missing

### PR DESCRIPTION
**Pull request by yalh76**
I do my Maniack ^^

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
I actually do prefer to use dbname instead of dbuser ;)

**Comment by yalh76** [comment]
> 
> 
> I actually do prefer to use dbname instead of dbuser ;)

me too but as `db_user` has been implemented in some scripts but not all. Or we remove `db_user` in all scripts or have to implement db_user in all scripts ^^

But as there are some apps, for example Mastodon, that don't use dthe same db_user and db_name...

https://github.com/YunoHost-Apps/mastodon_ynh/blob/eeec0653ac3e2c38bf6c46c93fdecf28d8dae1ab/scripts/install#L126-L127

Maybe better to implement db_user in all scripts

**Comment by maniackcrudelis** [comment]
I found that using db_user is useless. Since we usually copy db_name to make db_user.
But using db_user could as well give a clear info about what's we really dealing with.

I have no strong opinion on this.

**Comment by yalh76** [comment]
> 
> 
> I found that using db_user is useless. Since we usually copy db_name to make db_user.
> But using db_user could as well give a clear info about what's we really dealing with.
> 
> I have no strong opinion on this.

Me neither, maybe guys from @YunoHost-Apps/apps-group can give their opinion.

- Option 1: remove db_user variable
- Option 2 : implement db_user in all scripts

**Comment by kay0u** [comment]
¯\\\_(ツ)\_/¯

**Comment by yalh76** [comment]
> 
> 
> ¯\_(ツ)_/¯

MDR... it doesn't help ^^

**Comment by kay0u** [comment]
We can keep this one, I'll close #87

Will be merge in 3 days

**Pull request merged**
