### PR TITLE
Php fpm

### PR DESCRIPTION
**Pull request by yalh76**
I propose to change the php-fpm step order.

I'm considering package using php7.1, 7.2, etc...  and installing php7.1, 7.2, etc... during the `INSTALL DEPENDENCIES` step

- during removal it's better to have php-fpm removal before dependencies removal
- during restore we must first install dependencies and then restore php-fpm

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
If you use php 7.1 or more, you're suppose to use the specific helper dedicated to.
Your dependencies should then be installed or removed by this helper, not `ynh_install_app_dependencies`

**Comment by yalh76** [comment]
> 
> 
> If you use php 7.1 or more, you're suppose to use the specific helper dedicated to.
> Your dependencies should then be installed or removed by this helper, not `ynh_install_app_dependencies`

Yes but I usually put `ynh_install_php --phpversion` at `DEPENDENCIES ` Step

**Comment by maniackcrudelis** [comment]
Would be better to use a specific part for this step.

**Comment by yalh76** [comment]
OK, I will do that

**Pull request closed without merging**
